#!/bin/bash

bspc config border_width        5
bspc config window_gap         5
bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

if [[ `bspc query -M | wc -l` == 2 ]]
then
    bspc monitor HDMI1 -d I II III IV V VI VII VIII IX
    bspc monitor VGA1 -d X
else
    bspc monitor -d term web code music
fi

bspc rule -a Emacs desktop=^3 state=tiled

# mouse support
bspc config pointer_modifier mod4
bspc config click_to_focus true

# manage windows left from previous session
bspc control --adopt-orphans
bspc config wm_name LG3D
sxhkd &
polybar top &
xrdb -merge ~/.Xresources
bspc config normal_border_color $color0
bspc config focused_border_color $color7
bspc config active_border_color $color1
bspc config urgent_border_color $color1
bspc config presel_feedback_color $color7
compton -b --config ~/.compton
~/.local/bin/wal -R
redshift &
~/.local/bin/mopidy & 
export _JAVA_AWT_WM_NONREPARENTING=1
